root: true
parserOptions:
  project: tsconfig.json
  sourceType: module
env:
  node: true
  jest: true
extends:
  - '@monkee/eslint-config/typescript'
rules:
  'no-console': error
overrides:
  - files: ['migrations/*.ts', 'test/files/typeorm-migrations/*.ts']
    rules:
      '@typescript-eslint/naming-convention': 0
settings:
  import/resolver:
    typescript:
      project: './tsconfig.json'
